orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

    jobs:
      build:
        executor:
          name: name/default
          tag: '10.4'
        steps:
          - checkout
          - node/with-cache
          steps:
            -run npm install
          -run: npm run test
