version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test:
    executor:
      name: name/default
      tag: "10.4"
    steps:
      - checkout
      - node/install-packages:
      - run:
          command: npm install
      - run:
          command: npm run test
workflows:
  version: 2.1
  test:
    jobs:
      - test
