orbs:
  node: circleci/node@2.0.2

version: 2.1

jobs:
  one:
    docker: #it uses the docker executor
      - image: circleci/ruby:2.4.1 #specifically, a docker iamge with ruby 2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD #
    steps:
      - run: npm install
      - run: npm run test

workflows:
  version: 2.1
  test npm run test:
    jobs: -one
